// Copyright (c) 2022 DHGMS Solutions and Contributors. All rights reserved.
// This file is licensed to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.CommandLine;
using System.IO;

namespace Whipstaff.Testing.CommandLine
{
    /// <summary>
    /// Helpers for testing command line applications using xUnit.
    /// </summary>
    public static class XUnitTestHelpers
    {
        /// <summary>
        /// Creates a test configuration for integrating a console application with command-line functionality.
        /// </summary>
        /// <param name="outputWriter">A <see cref="StringWriter"/> instance used to capture standard output generated by the command-line interface.</param>
        /// <param name="errorWriter">A <see cref="StringWriter"/> instance used to capture error output generated by the command-line interface.</param>
        /// <returns>A <see cref="InvocationConfiguration"/> object configured with the specified root command, output writer,
        /// and error writer.</returns>
        public static InvocationConfiguration CreateTestConsoleIntegration(
            StringWriter outputWriter,
            StringWriter errorWriter)
        {
            return new InvocationConfiguration
            {
                Output = outputWriter,
                Error = errorWriter,
            };
        }
    }
}
